version: "3.9"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
